export default {
  schemeWeaver: {
    searchContentTypes: 'Search content types...',
    searchSchemaTypes: 'Search schema types...',
    loading: 'Loading...',
    loadingMappings: 'Loading schema mappings...',
    loadingSchemaTypes: 'Loading schema types...',
    loadingProperties: 'Loading property mappings...',
    noResults: 'No results found.',
    noSchemaTypes: 'No schema types found.',
    noMapping: 'No Schema.org Mapping',
    noMappingDescription: 'This content type has not been mapped to a Schema.org type yet.',
    notMapped: 'Not mapped',
    mapped: 'Mapped',
    unmapped: 'Unmapped',
    properties: 'Properties',
    save: 'Save Mapping',
    saving: 'Saving...',
    cancel: 'Cancel',
    retry: 'Retry',
    refresh: 'Refresh',
    generate: 'Generate',
    generating: 'Generating...',
    map: 'Map',
    mapToSchema: 'Map to Schema.org',
    editMapping: 'Edit mapping',
    deleteMapping: 'Delete mapping',
    deleteMappingConfirm: 'Delete the Schema.org mapping for "{0}"? This cannot be undone.',
    noMappingExists: 'No mapping exists for this content type',
    previewJsonLd: 'Preview JSON-LD',
    autoMap: 'Auto-map',
    autoMapSchema: 'Auto-map Schema',
    generatePreview: 'Generate Preview',
    selectSchemaType: 'Select Schema.org Type',
    mapProperties: 'Map Properties',
    generateContentType: 'Generate Content Type from Schema.org',
    contentTypeGenerated: 'Content type generated successfully',
    contentTypeName: 'Content Type Name',
    contentTypeAlias: 'Content Type Alias',
    selectProperties: 'Select Properties',
    selectPropertiesDescription: 'Choose which Schema.org properties to include as document type properties:',
    contentType: 'Content Type',
    schemaType: 'Schema Type',
    status: 'Status',
    actions: 'Actions',
    back: 'Back',
    schemaOrgMapping: 'Schema.org Mapping',
    propertyMappings: 'Property Mappings',
    contentTypeSettings: 'Content Type Settings',
    mappedTo: 'mapped to',
    extends: 'extends',
    generateFromSchema: 'Generate from Schema.org',
    noPreviewData: 'No JSON-LD data to preview',
    jsonLdPreview: 'JSON-LD Preview',
    copyToClipboard: 'Copy to clipboard',
    copy: 'Copy',
    mappingDeleted: 'Mapping deleted successfully',
    mappingSaved: 'Mapping saved successfully',
    preview: 'Preview',
    schemaProperty: 'Schema Property',
    type: 'Type',
    source: 'Source',
    value: 'Value',
    confidence: 'Confidence',
    confidenceHigh: 'High',
    confidenceMedium: 'Medium',
    confidenceLow: 'Low',
    sourceCurrentNode: 'Current Node',
    sourceStaticValue: 'Static Value',
    sourceParentNode: 'Parent Node',
    sourceAncestorNode: 'Ancestor Node',
    sourceSiblingNode: 'Sibling Node',
    enterStaticValue: 'Enter static value...',
    staticValueFor: 'Static value for',
    contentTypeAliasPlaceholder: 'Content type alias...',
    valid: 'Valid',
    invalid: 'Invalid',
    publishRequired: 'Publish this content first, then refresh to preview JSON-LD output.',
    noMappingForPreview: 'No Schema.org mapping exists for this content type. Map it first from the document type editor.',
    sourceBlockContent: 'Block Content',
    sourceMediaUrl: 'Media URL (auto)',
    sourceContentPicker: 'Content Picker',
    nestedSchemaType: 'Nested Schema Type',
    configureNestedMapping: 'Configure Block Mapping',
    editorType: 'Editor',
    blockList: 'Block List',
    blockGrid: 'Block Grid',
    mediaPicker: 'Media',
    contentPicker: 'Picker',
    richText: 'Rich Text',
    autoUrl: 'auto URL',
    nestedMappingCount: 'mappings',
    wrapInType: 'Wrap in Type',
    autoMapNested: 'Auto-map',
    autoMapNestedHint: 'Automatically match block properties to schema properties',
    wrapAutoDetected: 'Auto-detected',
    blockElementType: 'Block Element Type',
    nestedMappings: 'Nested Mappings',
    hideUnmapped: 'Hide unmapped properties',
    unmappedProperties: 'unmapped properties',
    showMoreProperties: 'Show {0} more properties',
    showFewerProperties: 'Show fewer properties',
    noMappedProperties: 'No properties mapped yet. Use the dropdown below to add schema properties, or click Auto-map.',
    sourceComplexType: 'Schema.org Type',
    selectSubType: 'Select type',
    subPropertyMappings: 'Type Properties',
    configureSubType: 'Configure sub-type properties using the expand arrow',
    selectContentType: 'Select Content Type',
    loadingContentTypes: 'Loading content types...',
    noContentTypes: 'No content types found.',
    pickContentType: 'Pick content type...',
    changeContentType: 'Change content type',
    selectProperty: 'Select property...',
    searchProperties: 'Search properties...',
    noProperties: 'No properties found.',
    selectNestedType: 'Select nested type...',
    preConfigure: 'Pre-configured',
    inherited: 'Inherited',
    inheritedDescription: 'When enabled, this schema will also be output on all descendant pages.',
    next: 'Next',
    noBlockTypesHint: 'No block element types found for this property. Enter an alias manually:',
    selectBlockTypeHint: 'Select the block element type that contains the content for each',
    from: 'from',
    blockPropertyPlaceholder: 'Block property alias...',
    resolverConfigJson: 'Resolver Config JSON',
    staticValueLabel: 'Static value',
    propertyLabel: 'Property',
    expand: 'Expand',
    collapse: 'Collapse',
    pickSourceOrigin: 'Choose Source Origin',
    originCurrentNodeDescription: 'Map from a property on this content node',
    originStaticValueDescription: 'Use a fixed text value',
    originRelatedContent: 'Related Content',
    originRelatedContentDescription: 'Map from a related content node',
    originBlockContentDescription: 'Map from block list or grid items',
    originComplexTypeDescription: 'Build from Schema.org sub-type properties',
    originParentDescription: 'The direct parent node',
    originAncestorDescription: 'Walk up the content tree',
    originSiblingDescription: 'A node at the same level',
    showUnmappedProperties: 'Show {0} unmapped properties', // kept for backwards compatibility
    pleaseEnterNestedSchemaType: 'Please enter a nested schema type name first.',
    pleaseSelectBlockContentProperty: 'Please select a block content property first.',
    failedToLoadMapping: 'Failed to load mapping',
    failedToSave: 'Failed to save',
    failedToLoadMappingData: 'Failed to load mapping data',
    failedToDeleteMapping: 'Failed to delete mapping',
    failedToGeneratePreview: 'Failed to generate preview',
    failedToGenerateContentType: 'Failed to generate content type',
    autoMapFailed: 'Auto-map failed',
    done: 'Done',
    change: 'Change',
    set: 'Set',
    none: '-- None --',
    configureComplexType: 'Configure Schema.org Type',
    complexTypeMappings: 'Type Property Mappings',
    selectSchemaSubType: 'Select Schema.org Sub-Type',
    complexTypeConfigured: 'Type mapping configured',
    propertyMappingsConfigured: 'property mappings configured for',
    failedToResolveContentType: 'Failed to resolve content type',
    copiedToClipboard: 'Copied to clipboard',
    copyFailed: 'Failed to copy to clipboard',
    failedToLoadContentTypes: 'Failed to load content types',
    failedToLoadSchemaTypes: 'Failed to load schema types',
    searchFailed: 'Search failed',
    noBlockTypesConfigureHint: 'Configure block types in the data type settings to enable selection here.',
    selectAtLeastOneProperty: 'Select at least one property to generate.',
    selectASchemaType: 'Select a schema type to continue.',
    noPropertiesToMap: 'No properties available to map for this schema type.',
    addSchemaProperty: 'Add schema property',
    addSchemaPropertyDescription: 'Search and select a schema property to add to the mapping.',
    popularProperties: 'Popular',
    complexTypeProperties: 'Complex Types',
    otherProperties: 'Other',
    removeProperty: 'Remove',
    // showMoreProperties is defined above and shared with the nested-type modal disclosure.
    hideAdditionalProperties: 'Hide additional properties',

    // AI features (require SchemeWeaver.AI satellite package)
    aiAnalyse: 'AI Analyse',
    aiAnalyseAll: 'AI Analyse All',
    aiAutoMap: 'AI Auto-map',
    aiSuggesting: 'AI is analysing...',
    aiSuggestion: 'AI Suggestion',
    aiConfidence: 'AI Confidence',
    aiReasoning: 'Reasoning',
    aiNotAvailable: 'Umbraco.AI is not installed. Install Umbraco.Community.SchemeWeaver.AI for AI-powered mapping.',
    aiAnalyseAllDescription: 'Use AI to analyse all content types and suggest Schema.org mappings.',
    aiBulkResults: 'AI Analysis Results',
    aiApply: 'Apply',
    aiApplyAll: 'Apply All',
    aiSkip: 'Skip',
    aiSuggestedSchema: 'AI Suggested Schema',
    aiAnalysing: 'Analysing with AI...',
    aiApplying: 'Applying mappings...',
    aiNoSuggestions: 'AI could not determine a suitable schema type for this content type.',
    aiBulkComplete: 'AI analysis complete',
    aiAnalysisFailed: 'AI analysis failed. Please try again.',
    aiAutoMapFailed: 'AI auto-map failed. Please try again.',

    // Workspace context errors
    workspaceContextUnavailable: 'Could not connect to the SchemeWeaver workspace context.',

    // Modal aria-labels
    schemaTypesListLabel: 'Schema.org types',
    propertiesListLabel: 'Properties',
    schemaSelectListLabel: 'Schema selection',

    // Workspace-view tab labels (kept short — they appear on document type / content tabs)
    workspaceViewSchemaOrg: 'Schema.org',
    workspaceViewJsonLd: 'JSON-LD',

    // Built-in property display names shown in the property combobox
    builtInUrl: 'URL (Built-in)',
    builtInName: 'Name (Built-in)',
    builtInCreateDate: 'Create Date (Built-in)',
    builtInUpdateDate: 'Update Date (Built-in)',

    // Parameterised strings
    schemaPropertyCount: '{0} properties',
    loadingEllipsis: 'Loading...',
    wrapPrefix: 'wrap',
    mapPropertiesForType: 'Map Properties — {0}',
    nestedMappingForType: 'Nested Mapping — {0}',
    valueForProperty: 'Value for {0}',
    propertyAliasLabel: 'Property alias for {0}',
    staticValueForProperty: 'Static value for {0}',
    nestedTypeForProperty: 'Nested type for {0}',
    wrapInTypeForProperty: 'Wrap-in type for {0}',
  },
};
