export default {
  schemeWeaver: {
    dashboardHeadline: 'Schema.org Mappings',
    searchContentTypes: 'Search content types...',
    searchSchemaTypes: 'Search schema types...',
    loading: 'Loading...',
    loadingMappings: 'Loading schema mappings...',
    loadingSchemaTypes: 'Loading schema types...',
    loadingProperties: 'Loading property mappings...',
    noResults: 'No content types found matching your search.',
    noSchemaTypes: 'No schema types found.',
    noMapping: 'No Schema.org Mapping',
    noMappingDescription: 'This content type has not been mapped to a Schema.org type yet.',
    notMapped: 'Not mapped',
    mapped: 'Mapped',
    unmapped: 'Unmapped',
    properties: 'properties',
    save: 'Save Mapping',
    saving: 'Saving...',
    cancel: 'Cancel',
    retry: 'Retry',
    refresh: 'Refresh',
    generate: 'Generate',
    generating: 'Generating...',
    map: 'Map',
    mapToSchema: 'Map to Schema.org',
    editMapping: 'Edit mapping',
    deleteMapping: 'Delete mapping',
    previewJsonLd: 'Preview JSON-LD',
    autoMap: 'Auto-map',
    autoMapSchema: 'Auto-map Schema',
    generatePreview: 'Generate Preview',
    selectSchemaType: 'Select Schema.org Type',
    mapProperties: 'Map Properties',
    generateContentType: 'Generate Content Type from Schema.org',
    contentTypeName: 'Content Type Name',
    contentTypeAlias: 'Content Type Alias',
    selectProperties: 'Select Properties',
    selectPropertiesDescription: 'Choose which Schema.org properties to include as document type properties:',
    contentType: 'Content Type',
    schemaType: 'Schema Type',
    status: 'Status',
    actions: 'Actions',
    back: 'Back',
    schemaOrgMapping: 'Schema.org Mapping',
    propertyMappings: 'Property Mappings',
    contentTypeSettings: 'Content Type Settings',
    mappedTo: 'mapped to',
    extends: 'extends',
    generateFromSchema: 'Generate from Schema.org',
    noPreviewData: 'No JSON-LD data to preview',
    jsonLdPreview: 'JSON-LD Preview',
    copyToClipboard: 'Copy to clipboard',
    copy: 'Copy',
    mappingDeleted: 'Mapping deleted successfully',
    mappingSaved: 'Mapping saved successfully',
    preview: 'Preview',
  },
};
