export default {
  schemeWeaver: {
    dashboardHeadline: 'Schema.org Mappings',
    searchContentTypes: 'Search content types...',
    searchSchemaTypes: 'Search schema types...',
    loading: 'Loading...',
    loadingMappings: 'Loading schema mappings...',
    loadingSchemaTypes: 'Loading schema types...',
    loadingProperties: 'Loading property mappings...',
    noResults: 'No content types found matching your search.',
    noSchemaTypes: 'No schema types found.',
    noMapping: 'No Schema.org Mapping',
    noMappingDescription: 'This content type has not been mapped to a Schema.org type yet.',
    notMapped: 'Not mapped',
    mapped: 'Mapped',
    unmapped: 'Unmapped',
    properties: 'Properties',
    save: 'Save Mapping',
    saving: 'Saving...',
    cancel: 'Cancel',
    retry: 'Retry',
    refresh: 'Refresh',
    generate: 'Generate',
    generating: 'Generating...',
    map: 'Map',
    mapToSchema: 'Map to Schema.org',
    editMapping: 'Edit mapping',
    deleteMapping: 'Delete mapping',
    previewJsonLd: 'Preview JSON-LD',
    autoMap: 'Auto-map',
    autoMapSchema: 'Auto-map Schema',
    generatePreview: 'Generate Preview',
    selectSchemaType: 'Select Schema.org Type',
    mapProperties: 'Map Properties',
    generateContentType: 'Generate Content Type from Schema.org',
    contentTypeName: 'Content Type Name',
    contentTypeAlias: 'Content Type Alias',
    selectProperties: 'Select Properties',
    selectPropertiesDescription: 'Choose which Schema.org properties to include as document type properties:',
    contentType: 'Content Type',
    schemaType: 'Schema Type',
    status: 'Status',
    actions: 'Actions',
    back: 'Back',
    schemaOrgMapping: 'Schema.org Mapping',
    propertyMappings: 'Property Mappings',
    contentTypeSettings: 'Content Type Settings',
    mappedTo: 'mapped to',
    extends: 'extends',
    generateFromSchema: 'Generate from Schema.org',
    noPreviewData: 'No JSON-LD data to preview',
    jsonLdPreview: 'JSON-LD Preview',
    copyToClipboard: 'Copy to clipboard',
    copy: 'Copy',
    mappingDeleted: 'Mapping deleted successfully',
    mappingSaved: 'Mapping saved successfully',
    preview: 'Preview',
    schemaProperty: 'Schema Property',
    type: 'Type',
    source: 'Source',
    value: 'Value',
    confidence: 'Confidence',
    confidenceHigh: 'High',
    confidenceMedium: 'Medium',
    confidenceLow: 'Low',
    sourceCurrentNode: 'Current Node',
    sourceStaticValue: 'Static Value',
    sourceParentNode: 'Parent Node',
    sourceAncestorNode: 'Ancestor Node',
    sourceSiblingNode: 'Sibling Node',
    enterStaticValue: 'Enter static value...',
    staticValueFor: 'Static value for',
    contentTypeAliasPlaceholder: 'Content type alias...',
    valid: 'Valid',
    invalid: 'Invalid',
    publishRequired: 'Preview requires published content of this type',
    noMappingForPreview: 'No Schema.org mapping exists for this content type. Map it first from the document type editor.',
    sourceBlockContent: 'Block Content',
    sourceMediaUrl: 'Media URL (auto)',
    sourceContentPicker: 'Content Picker',
    nestedSchemaType: 'Nested Schema Type',
    configureNestedMapping: 'Configure Block Mapping',
    editorType: 'Editor',
    blockList: 'Block List',
    blockGrid: 'Block Grid',
    mediaPicker: 'Media',
    contentPicker: 'Picker',
    richText: 'Rich Text',
    builtIn: 'Built-in',
    autoUrl: 'auto URL',
    nestedMappingCount: 'mappings',
    wrapInType: 'Wrap in Type',
    blockElementType: 'Block Element Type',
    nestedMappings: 'Nested Mappings',
    hideUnmapped: 'Hide unmapped properties',
    unmappedProperties: 'unmapped properties',
    noMappedProperties: 'No properties are mapped yet. Click "Show unmapped properties" below to configure mappings.',
    sourceComplexType: 'Schema.org Type',
    selectSubType: 'Select type',
    subPropertyMappings: 'Type Properties',
    configureSubType: 'Configure sub-type properties using the expand arrow',
    selectContentType: 'Select Content Type',
    loadingContentTypes: 'Loading content types...',
    noContentTypes: 'No content types found.',
    pickContentType: 'Pick content type...',
    changeContentType: 'Change content type',
    selectProperty: 'Select Property',
    searchProperties: 'Search properties...',
    noProperties: 'No properties found.',
    selectProperty: 'Select property...',
    selectNestedType: 'Select nested type...',
    preConfigure: 'Pre-configured',
    inherited: 'Inherited',
    inheritedDescription: 'When enabled, this schema will also be output on all descendant pages.',
  },
};
